### ISSUE TITLE
Sylvania Dimming Switch detected as "MultiLevelButton" (no spaces) with generic "THING" icon (should get a clearer icon of its own)

### ISSUE THREAD

**Issue by dholbert** [mozilla-iot/gateway#1419]
STEPS TO REPRODUCE:
 1. Pair a [SYLVANIA SMART+ ZigBee 2 Button Dimming Switch](https://consumer.sylvania.com/our-products/smart/product-info/zigbee/sylvania-smart-zigbee-2-button-dimming-switch/index.jsp) with your gateway
 2. Look at the icon for the switch.

ACTUAL RESULTS:
 - the switch gets detected as a "MultiLevelButton"
 - there's no icon next to it on the "Add Thing" page
 - After I've added it, it gets a generic icon that just says "THING" (on my "Things" page)

EXPECTED RESULTS:
 - Perhaps it should be detected as a "Multi Level Switch"? (not MultiLevelButton)
 - It should have an appropriate icon. (We have such an icon for Multi Level Switch, which I can see if I enable the Virtual Things add-on -- there's a vertical partially-filled bar icon for that thing, but not for my physical switch.)

**Comment by dholbert** [comment]
(Also, just to be clear, this switch does seem to *work correctly* -- this github issue is purely about the cosmetics of getting an icon/classification that makes sense.)

**Comment by dhylands** [comment]
Just FYI: this is currently being discussed over here:
https://github.com/mozilla-iot/schemas/issues/15

**Comment by dhylands** [comment]
Also see https://github.com/mozilla-iot/zigbee-adapter/pull/62 for updated screenshots as to how this might look (assuming PR is approved and lands)

**Comment by mrstegeman** [comment]
@dhylands I believe this should be fixed now, correct?

**Comment by dhylands** [comment]
Yes - it currently uses the MultiLevelSwitch type (which I think is still incorrect). I think it should have a type like MultiLevelButton.

Anyways, it looks like a MultiLevelSwitch, so you can see the on/off status and level from the main UI and they update if you manipulate the switch.

It also generates the following events:
* 1-pressed
* 2-pressed
* 1-longPressed
* 2-longPressed
* 1-released
* 2-released

the events with a 1 correspond to the top button and the events with a 2 correspond to the bottom button.

**Comment by dhylands** [comment]
![screenshot from 2018-10-17 13-24-48](https://user-images.githubusercontent.com/127500/47191335-8aacba00-d2fb-11e8-85c3-3ad723753047.png)
