### ISSUE TITLE
Lockup gateway with /things websocket testcase

### ISSUE THREAD

**Issue by cdelston0** [mozilla-iot/gateway#2367]
I can reliably (almost every time, but not quite) lock up the gateway process with the test code from: https://github.com/cdelston0/gateway-test

Steps to reproduce:
- Start gateway and ensure that the native webthings addon is enabled
- Run the following test class:

python3 test.py --gateway-url=http://localhost:8080 --gateway-user=testuser@email.com --gateway-password=testpass --things-quantity=20 --property-changes=100 MultipleThingProfiling

This test class runs multiple test cases, and does the following:
- creates 20 native webthing instances on the local machine
- adds the native webthing instances to the gateway
- spams the gateway with property change requests via POST to /things/<thingid> urls
- spams the gateway with property change requests via websocket to the /things websocket

The result is that the gateway becomes entirely unresponsive - attempting to access the gateway UI no longer works.

20 things and 100 property change requests seems to be important, I have seen the issue occur at lower numbers of each, but it's pretty reproducible with these numbers.

It always seems to lock up during the test case test_4_property_change_via_WS_no_wait_for_gateway, but running this test case on it's own doesn't seem to be enough.

**Comment by cdelston0** [comment]
When the gateway is locked up, I see the following in the gateway log:

2019-12-13 14:05:06.790 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
2019-12-13 14:05:06.790 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
2019-12-13 14:05:06.790 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
2019-12-13 14:05:06.791 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
2019-12-13 14:05:06.791 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
2019-12-13 14:05:06.792 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
2019-12-13 14:05:06.792 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
2019-12-13 14:05:06.793 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
2019-12-13 14:05:06.793 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
2019-12-13 14:05:06.793 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
2019-12-13 14:05:06.794 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)

Hitting Ctrl-C to kill the gateway always returns the following:

^C2019-12-13 14:21:47.144 ERROR  : 
2019-12-13 14:21:47.144 ERROR  : /home/chris/Work/SanCloud/gateway/node_modules/nanomsg/lib/index.js:150
        this.emit('error', new Error(nn.Err()));
                           ^
2019-12-13 14:21:47.144 ERROR  : Error: Interrupted system call
    at Socket._protect (/home/chris/Work/SanCloud/gateway/node_modules/nanomsg/lib/index.js:150:28)
    at Socket._send (/home/chris/Work/SanCloud/gateway/node_modules/nanomsg/lib/index.js:179:17)
    at Socket.flush (/home/chris/Work/SanCloud/gateway/node_modules/nanomsg/lib/index.js:279:14)
    at Socket.<anonymous> (/home/chris/Work/SanCloud/gateway/node_modules/nanomsg/lib/index.js:210:30)

**Comment by cdelston0** [comment]
Note that once you have locked the gateway up in this way, it will have 20 webthings added. This will interfere with future test runs. I have the following convenience method to clear out ALL things in the gateway database:

python3 test.py --gateway-url=http://localhost:8080 --gateway-user=testuser@email.com --gateway-password=testpass cleanup_all_webthings

**Comment by mrstegeman** [comment]
I wonder if this might also be fixed by https://github.com/mozilla-iot/thing-url-adapter/pull/84

**Comment by cdelston0** [comment]
I believe the fix to thing-url-adapter michael mentions above made this bug less likely to occur, but it doesn't resolve the issue.

I have updated my test code (https://github.com/cdelston0/gateway-test/commit/64467816ee55e5ca436ab7eeda4e429c87fc19cf) to use multiprocessing instead of the prior multithreaded approach. This allows me to hit the gateway with requests at a faster rate, and thus makes triggering the issue more likely.

Current test as follows:

Start gateway on CPU 0 with:
taskset 0x1 node --inspect build/gateway.js

Run following test case on CPUS1-7 with:
taskset 0xF7 python3 test.py --gateway-url=http://localhost:8080 --gateway-user=testuser@email.com --gateway-password=testpass --things-quantity=100 --property-changes=50 MultipleThingProfiling.test_4_property_change_via_WS_no_wait_for_gateway

Michael: note that taskset is Linux flavoured, and I don't believe that there's a MacOS equivalent :(  Without it, the test harness will use all CPUs and that means when running a localhost test the gateway will have to compete with the test harness for CPU time. This may actually make the problem more likely to occur?

In my test runs, the gateway has usually locked no later than the property change with index 30. Once the gateway has locked up, I can no longer connect to the node debugging port - profiling and memory captures start but never finish. If I Ctrl-C the gateway process, the debugger catches the exception and stack trace, but this doesn't offer much more information than the console stack trace.

**Comment by cdelston0** [comment]
When the gateway locks up, the test harness will eventually timeout and claim that the property update sequences are correct - they're not, that's an error in the harness.

**Comment by mrstegeman** [comment]
Ok, I've been doing some testing with this. What I end up with appears to be a lockup with the _test_, not with the gateway. The below is from a Linux machine.

```
$ taskset 0xF7 python3 test.py  --gateway-url http://192.168.86.216:8080 --gateway-user mstegeman@mozilla.com --gateway-password password --things-quantity 100 --property-changes 50 MultipleThingProfiling.test_4_property_change_via_WS_no_wait_for_gateway
2019-12-18 20:29:54.189505 Waiting for 100 webthings
2019-12-18 20:29:59.152263 All webthings added
2019-12-18 20:30:08.460435 All webthings connected
--- Sending 50 property changes to 100 webthings via WS:// ( not waiting for gateway response)
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketProtocol13._receive_frame_loop() running at /usr/local/lib/python3.7/site-packages/tornado/websocket.py:1118> wait_for=<Future pending cb=[IOLoop.add_future.<locals>.<lambda>() at /usr/local/lib/python3.7/site-packages/tornado/ioloop.py:690, <TaskWakeupMethWrapper object at 0x7fbdd4918c10>()]> cb=[IOLoop.add_future.<locals>.<lambda>() at /usr/local/lib/python3.7/site-packages/tornado/ioloop.py:690]>
```

When that occurs, the gateway logging pauses at:
```
2019-12-18 11:30:13.773 INFO   : thing-url: getValue for property idx for: a testThing on port 8879 returning 48
```

However, while in that state, I'm still able to open the UI, set property values, etc., so that tells me that the gateway is not locked up.

**Comment by cdelston0** [comment]
That doesn't sound like the same state I'm seeing. The gateway UI is entirely unresponsive - pages reload to a blank blue screen.

I'm suspecting rate is very important, and I note that you're addressing your gateway by an IP address. Is the gateway running on the same machine as the test?

The test output you are seeing is from tearing down the testthing instances. It takes a looong time to tear these down (not sure why), but it has been my experience that eventually it will do so, and will start deleting the things from the gateway.

**Comment by mrstegeman** [comment]
> That doesn't sound like the same state I'm seeing. The gateway UI is entirely unresponsive - pages reload to a blank blue screen.

I haven't been able to get past the error I posted above.

> I'm suspecting rate is very important, and I note that you're addressing your gateway by an IP address. Is the gateway running on the same machine as the test?

No, different machine on the same network.

> The test output you are seeing is from tearing down the testthing instances. It takes a looong time to tear these down (not sure why), but it has been my experience that eventually it will do so, and will start deleting the things from the gateway.

I've seen the test succeed several times with no errors, but when it does fail, it's always in that same spot, and it never recovers.

**Comment by mrstegeman** [comment]
I should note that my setup is this:
* Gateway running on Macbook
* Test running inside python:3.7 Docker container on a Linux laptop

**Comment by cdelston0** [comment]
Any chance you want to retry with a localhost gateway?

Just tried it again, same result: unresponsive gateway and I consistently get the same backtrace that I posted above (interrupted syscall in a nanomsg send function).

For reference, the rate of "getValue for property" messages in my gateway console log is ~2500 per second - so pretty busy. It's hard to imagine a real world scenario for this.

**Comment by mrstegeman** [comment]
Ok, if I run the test inside a Docker container also running the gateway, things do lock up. Not really sure where to go from here, though... Hard to debug if we can't even attach a debugger!

**Comment by cdelston0** [comment]
I'll settle for it being reproducible for today, that's something. I don't know how much to read into the stack track returned when SIGINTing the node process. Is that telling us that it was in a syscall and it's been interrupted by SIGINT, or it's locked up because an interrupted syscall hasn't been handled?

**Comment by mrstegeman** [comment]
To me, it just looks like nanomsg was in the process of sending a message, but was interrupted by your SIGINT.

FYI, nanomsg is the transport layer between the gateway and add-ons.

I've run into other weirdness with nanomsg before, so I wonder if it's maybe just getting overwhelmed.

**Comment by cdelston0** [comment]
We could try increasing the nanomsg send and receive buffer sizes to see if that makes it harder to cause.

**Comment by mrstegeman** [comment]
Just seems like that should be unnecessary, given that it's just a local Unix domain socket.

**Comment by mrstegeman** [comment]
Potentially fixed by #2424.

**Comment by flatsiedatsie** [comment]
Just came accross this error too. "WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)".

**Comment by flatsiedatsie** [comment]
Still running into this issue.
