### ISSUE TITLE
GUI-defined GPIO doesn't shows up on Things screen

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#903]
The GpioAdapter 0.3.3 on Gateway 0.4.0 allows using the GUI to define the GPIOs.

<img width="1268" alt="capture 2018-04-18 a 16 30 54" src="https://user-images.githubusercontent.com/951776/38938798-b7cc6b58-4326-11e8-9587-1fe7a3d49fde.png">

No luck, the above defined GPIOs doesn't appear on the **Thing > Add Device** menu.

<img width="1268" alt="capture 2018-04-18 a 16 32 23" src="https://user-images.githubusercontent.com/951776/38938809-bd99bef0-4326-11e8-8520-cce7227aaa33.png">

Using the previous procedure shows the configuration file is empty.

```
$ cd ~/mozilla-iot/gateway/tools
$ 
$ ./config-editor.py gpio-adapter
{
  "gpios": []
}
$ 
```

What's going wrong?

**Comment by rei-vilo** [comment]
After modifying the configuration with...

```
$ cd ~/mozilla-iot/gateway/tools
$ ./config-editor.py -e gpio-adapter
```

...and relaunching with...

```
sudo systemctl restart mozilla-iot-gateway.service
```

...the GpioAdapter screen displays the configured GPIOs, but the Thing > Add Device menu stays empty.

<img width="1268" alt="capture 2018-04-18 a 16 39 50" src="https://user-images.githubusercontent.com/951776/38939101-797989e8-4327-11e8-9c47-6a2ad180b59e.png">

**Comment by sogaani** [comment]
I think gpio-adapter is dead.
Could you share your gateway log ```~/.mozilla-iot/log/run-app.log```?

**Comment by dhylands** [comment]
I can confirm this. I tried the following:
* Added pin 18, name LED, direction out, value 0 and pressed Apply.

Running tools/conf-editor.py gpio-adapter shows no configured pins.
If I click configure again it will show the configured pin, but if I then click the back arrow and then click configure again, it shows nothing.

Even manually running config-editor and entering the following:
```
{
  "gpios": [
    {
      "direction": "out",
      "name": "LED",
      "pin": 18,
      "value": 0
    }
  ]
}
```
If I then disable and re-enable the gpio-editor and run config-editor.py again the config is back to being an empty array.

**Comment by dhylands** [comment]
Even just following this sequence:
* Disable the GPIO addon
* Run config-editor.py to add a pin
* Enable the GPIO addon
The config editor now shows an empty config. The log shows:
```
2018-04-18 15:53:32.480 Unloading GpioAdapter
2018-04-18 15:53:32.484 gpio: Adapter: GpioAdapter unloaded
2018-04-18 15:54:09.747 Loading add-on: gpio-adapter
2018-04-18 15:54:10.425 gpio: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2018-04-18 15:54:10.466 gpio: Loading add-on for gpio-adapter from /home/pi/.mozilla-iot/addons/gpio-adapter
```

**Comment by rei-vilo** [comment]
That's sad, as the GPIOs provided an easy way to implement a quick-and-dirty demo.

Here is the `run-app.log`

```
$ cat ~/.mozilla-iot/log/run-app.log
nvm version
0.33.1
node version
v8.11.1
npm version
5.6.0
Starting gateway ...

> things-gateway@0.4.0 start /home/pi/mozilla-iot/gateway
> webpack && node build/gateway.js

(node:1017) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

[at-loader] Using typescript@2.7.2 from typescript and "tsconfig.json" from /home/pi/mozilla-iot/gateway/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 3.56 sec.
Hash: xxxxxxxxxxxxxxxxxxxxxx
Version: webpack 4.1.1
Time: 18518ms
Built at: 2018-4-18 17:49:33
                          Asset      Size  Chunks                    Chunk Names
                     gateway.js   317 KiB    main  [emitted]  [big]  main
                 gateway.js.map   355 KiB    main  [emitted]         main
../static/js/lib/stm_web.min.js  97.6 KiB          [emitted]         
Entrypoint main [big] = gateway.js gateway.js.map
[./src/addon-manager.js] 33.7 KiB {main} [built]
[./src/app-instance.js] 1.18 KiB {main} [built]
[./src/app.js] 8.15 KiB {main} [built]
[./src/constants.js] 3.42 KiB {main} [built]
[./src/controllers/commands_controller.js] 6.01 KiB {main} [built]
[./src/db.js] 14.6 KiB {main} [built]
[./src/log-timestamps.js] 3.19 KiB {main} [built]
[./src/models/jsonwebtoken.js] 3.79 KiB {main} [built]
[./src/router.js] 4.86 KiB {main} [built]
[./src/rules-engine/index.js] 2.59 KiB {main} [built]
[express] external "express" 42 bytes {main} [built]
[https] external "https" 42 bytes {main} [built]
[mustache-express] external "mustache-express" 42 bytes {main} [built]
[node-getopt] external "node-getopt" 42 bytes {main} [built]
[path] external "path" 42 bytes {main} [built]
    + 111 hidden modules

WARNING in ./src/addon-manager.js
38:9-16 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./src/addon-manager.js
 @ ./src/app.js
Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2018-04-18 17:49:38.575 Listening on port 4443
2018-04-18 17:49:38.623 Redirector listening on port 8080
2018-04-18 17:49:39.943 WebSocket opened on nonexistent thing gpio-18
2018-04-18 17:49:48.785 Checking for add-on updates...
2018-04-18 17:55:05.998 Fetching add-on https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/gpio-adapter-0.3.3-linux-arm-v8.tgz as /tmp/ta4chk/gpio-adapter.tar.gz
2018-04-18 17:55:08.822 Expanding add-on /tmp/ta4chk/gpio-adapter.tar.gz into /home/pi/.mozilla-iot/addons/gpio-adapter
2018-04-18 17:55:09.340 Loading add-on: gpio-adapter
2018-04-18 17:55:10.157 gpio: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2018-04-18 17:55:10.204 gpio: Loading add-on for gpio-adapter from /home/pi/.mozilla-iot/addons/gpio-adapter
2018-04-18 17:55:38.666 Unloading GpioAdapter
2018-04-18 17:55:38.671 gpio: Adapter: GpioAdapter unloaded
2018-04-18 17:55:42.569 Loading add-on: gpio-adapter
2018-04-18 17:55:43.337 gpio: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2018-04-18 17:55:48.919 Opened a new things socket
2018-04-18 17:56:48.925 Pairing timeout
2018-04-18 17:56:48.927 Thing was not added
2018-04-18 17:56:48.927 addNewThing cancelled
$ 
```

**Comment by dhylands** [comment]
I found the problem and I'm working on a fix. Should be fixed soon.

**Comment by rei-vilo** [comment]
Thanks!

**Comment by dhylands** [comment]
This should be fixed by https://github.com/mozilla-iot/gpio-adapter/pull/18

**Comment by dhylands** [comment]
Version 0.3.4 of the gpio adapter should fix the problem

**Comment by rei-vilo** [comment]
Unfortunately, release 0.3.4 didn't solve the problem.

An extra step is required:

```
sudo systemctl restart mozilla-iot-gateway.service
```

Shouldn't this step be managed by the GUI, for example when clicking on **Apply**?

**Comment by dhylands** [comment]
OK - I noticed that I had to restart the gateway as well, but I wasn't sure if this was just because of my development environment or not.

Pressing Apply stops and restarts the adapter.

I'll keep investigating...

**Comment by dhylands** [comment]
The restart seems to be a one-time thing. I can't reproduce requiring a restart once the 0.3.4 version of the gpio-adapter is installed.
